server:
   port: 8080
   servlet:
    contextPath: /agenda

spring:
  application:
    name: treinamento
  datasource:
    url: jdbc:postgresql://localhost:5432/
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456   
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none

jwt:
  secret: user